version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        restart: always
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1435:1433"
        environment:
            SA_PASSWORD: "MyStaticianDocker!@"
            ACCEPT_EULA: "Y"
        volumes:
            - "sqlvolume:/var/opt/mssql"
        restart: always

volumes:
  sqlvolume: